build:
	gcc -o task1 task1.c -std=c99
	gcc -o task2 task2.c -std=c99
	gcc -o task3 task3.c -std=c99
	gcc -o task4 task4.c -lm -std=c99
	gcc citire_parsare.c cautare_simpla.c cautare_avansata.c browser.c -o browser -lncurses
clean:
	rm task1 task2 task3 task4 browser

